### ISSUE TITLE
errod after warning

### ISSUE THREAD

**Issue by mariodmmariodm** [shmykelsa/AA-Tweaker#7] opened 2021-01-21 20:51 UTC
Hi, after the permissions and having accepted the warning does not start and the error continues to stop ... on Android 7.0

**Comment by shmykelsa** [comment] 2021-01-21 20:54
Hi,

could you please articulate better what's the exact issue?

What warning have you accepted?

Which permission are you talking about?

What error continues to stop?

Also could you please specify:

- Phone make and model
- Version of AA AIO TWEAKER
- Possibly, attach a logcat, cause that would help a lot

**Comment by mariodmmariodm** [comment] 2021-01-21 21:48
Hi, of course. Thanks for your answer. From today with Android auto version 6.0.615324 I no longer see the apps patched with phenotype then I discovered AA-Twaker the version here 1.1 is installed After that part I grant root permissions and the "I Understand" button appears I click and go in error it says "the AA AIO TWEAKER app has stopped" reopen the app if I reopen it and try again I get "the app keeps interrupting". the phone is an ulefone mix and I am attaching the logcat.

logcat: https://drive.google.com/file/d/1JNQbjMNlpukvZrEwcMPPxPZ58Bb8sFrH/view?usp=sharing

thanks,
mariodm

**Comment by shmykelsa** [comment] 2021-01-21 21:52
Could you please try latest version available? 

It's version 2.5 released today.

**Comment by mariodmmariodm** [comment] 2021-01-21 22:21
Done, version 2.5 installed, now it opens, but when I select an app it crashes again, and the same error appears as before, even if it seems to select it and I don't know if the patch, tomorrow I try in the car, cmq I am attaching a new logcat of the new error: https://drive.google.com/file/d/1P_PcMUBbXT3nkBPSCY1bbhmBF-k1kwcS/view?usp=sharing

thanks,
mariodm

**Comment by shmykelsa** [comment] 2021-01-21 22:54
Thanks for this.

The root cause has been found and it will be fixed in the upcoming version.

**Comment by mariodmmariodm** [comment] 2021-01-22 05:07
Grazie a te Gabriele e buon lavoro!

**Comment by shmykelsa** [comment] 2021-01-22 10:07
Fixed [with 2.6](https://github.com/shmykelsa/AA-Tweaker/releases/tag/v2.6). Please feel fre to reopen issue if issue is still present.

**Closed by shmykelsa** 2021-01-22 10:07 UTC

**Comment by mariodmmariodm** [comment] 2021-01-23 14:57
Hi now with 2.6 there are no more crashes, but in android auto version 6.0.615334 I don't see the apps after the patch, but it also happens to me with phenotype, it doesn't give errors, but then in the car I only see the basic apps of android and not aamirror or screen2auto ... They tell me it could depend on the new magisk version 21.4? do you have this problem? thanks

**Comment by shmykelsa** [comment] 2021-01-23 15:43
I have the same Android Auto version, Magisk 20.4 and apps are visible just fine. 

Honestly, I haven't had such reports of apps missing after using my app.

**Comment by mariodmmariodm** [comment] 2021-01-23 15:47
20.4? We are a Magisk 21.4, do you understand that? Now I try with downgrade at 21.3..

**Comment by shmykelsa** [comment] 2021-01-23 15:49
I know you are on Magisk 21.4, I just stated my own Magisk version.

**Comment by mariodmmariodm** [comment] 2021-01-23 16:02
I understand, but with magisk 21.4 have you tried? ... with magisk 21.3 now everything seems ok ...

**Comment by shmykelsa** [comment] 2021-01-23 20:21
For the sake of trying I've installed Magisk 21.4 and everything is right.

**Comment by mariodmmariodm** [comment] 2021-01-24 06:44
Ah then the problem will be android 7 or other, strange ... with magisk 21.3 it works but now I automatically activate the new android auto multi display mode that does not seem to be deactivated from the options, and the car screen is small and therefore it gets tough, just to entertain you ... https://photos.app.goo.gl/6yryVoKnPmRUbqjk9  Bah, I'll understand how ... thanks for the support!
